/************************************************************
 * Project: 업무 효율을 위한 맞춤형 대시보드 및 AI 비서 솔루션 구축 프로젝트
 * File: init_db.sql
 * Description: 15개 전체 테이블 스키마 및 초기 데이터 (무결성 보장)
 ************************************************************/

-- 1. 기존 테이블 삭제 
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CUSTOMER_MEMO, ORDER_DETAIL, ORDERS, PURCHASE_DETAIL, PURCHASE;
DROP TABLE IF EXISTS PRODUCT_COST_LOG, PRODUCT_PRICE_LOG, PRODUCT;
DROP TABLE IF EXISTS HIVE_INSTALL, HIVE_INSPECTION, HIVE_STATUS_LOG, HIVE;
DROP TABLE IF EXISTS HIVE_STATUS, WEATHER, USER, CUSTOMER;
SET FOREIGN_KEY_CHECKS = 1;

-- 2. USER 테이블 
CREATE TABLE USER(
  SYS_ID     INT                   NOT NULL AUTO_INCREMENT,
  LOGIN_ID   VARCHAR(20)           NOT NULL,
  PASSWORD   VARCHAR(255)          NOT NULL,
  ROLE       ENUM('ADMIN','STAFF') NOT NULL DEFAULT 'ADMIN',
  CREATED_AT TIMESTAMP             NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SYS_ID)
);

-- 3. CUSTOMER 테이블
CREATE TABLE CUSTOMER(
  CUSTOMER_ID    VARCHAR(20)                         NOT NULL,
  COMPANY_NAME   VARCHAR(50)                         NULL,
  BUSINESS_NO    VARCHAR(50)                         NULL,
  CONTACT_PERSON VARCHAR(50)                         NOT NULL,
  CONTACT        VARCHAR(50)                         NOT NULL,
  EMAIL          VARCHAR(100)                        NULL,
  COUNTRY        VARCHAR(50)                         NULL,
  ADDRESS        TEXT                                NULL,
  BANK           VARCHAR(50)                         NULL,
  ACCOUNT_NO     VARCHAR(50)                         NULL,
  ACCOUNT_NAME   VARCHAR(50)                         NULL,
  LAST_ORDER     DATE                                NULL,
  REG_DATE       DATE                                NOT NULL,
  MEMO           TEXT                                NULL,
  SUMMARY_TIME   TIMESTAMP                           NULL,
  STATUS         ENUM('ACTIVE','DORMANT','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  CLASS          ENUM('CUSTOMER', 'VENDER')          NOT NULL DEFAULT 'CUSTOMER' COMMENT '고객 OR 생산',
  PRIMARY KEY (CUSTOMER_ID)
);

-- 4. CUSTOMER_MEMO 테이블 
CREATE TABLE CUSTOMER_MEMO(
  CUSTOMER_ID VARCHAR(20) NOT NULL,
  MEMO_NO     INT         NOT NULL DEFAULT 1,
  MEMO_TEXT   TEXT        NULL,
  DATE        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SYS_ID      INT         NOT NULL DEFAULT 1,
  PRIMARY KEY (CUSTOMER_ID, MEMO_NO) 
);

-- 5. HIVE 테이블
CREATE TABLE HIVE(
  HIVE_ID      VARCHAR(50) NOT NULL,
  LOCATION     VARCHAR(20) NULL,
  FRAME_AMOUNT INT         NULL     DEFAULT 1,
  SUPER_AMOUNT INT         NULL     DEFAULT 1,
  INSTALL      VARCHAR(50) NULL,
  PRIMARY KEY (HIVE_ID)
);

-- 6. HIVE_INSPECTION 테이블
CREATE TABLE HIVE_INSPECTION(
  INS_ID    VARCHAR(50) NOT NULL,
  HIVE_ID   VARCHAR(50) NOT NULL,
  STATUS_ID INT         NOT NULL DEFAULT 1 COMMENT 'CODE. ',
  INS_TIME  TIMESTAMP   NULL     DEFAULT CURRENT_TIMESTAMP COMMENT 'inspection time',
  MEMO      TEXT        NULL    ,
  SYS_ID    INT         NOT NULL DEFAULT 1,
  PRIMARY KEY (INS_ID)
);

-- 7. HIVE_INSTALL 테이블
CREATE TABLE HIVE_INSTALL(
  HIVE_ID    VARCHAR(50) NOT NULL,
  ITEM_ROW   INT         NOT NULL DEFAULT 1,
  PRODUCT_ID VARCHAR(20) NOT NULL COMMENT '외부 제품도 등록하게',
  DATE       DATE        NOT NULL,
  SYS_ID     INT         NOT NULL DEFAULT 1,
  PRIMARY KEY (HIVE_ID, ITEM_ROW)
);

-- 8. HIVE_STATUS 테이블
CREATE TABLE HIVE_STATUS(
  STATUS_ID   INT         NOT NULL DEFAULT 1 COMMENT 'CODE. ',
  STATUS_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (STATUS_ID)
);

-- 9. HIVE_STATUS_LOG 테이블
CREATE TABLE HIVE_STATUS_LOG(
  LOG_ID    VARCHAR(50)  NOT NULL,
  HIVE_ID   VARCHAR(50)  NOT NULL,
  SENSOR    VARCHAR(20)  NULL    ,
  WEIGHT    DECIMAL(5,2) NULL    ,
  TEMP      DECIMAL(5,2) NULL    ,
  HUMI      DECIMAL(5,2) NULL    ,
  CO2       DECIMAL(6,2) NULL    ,
  TIME      TIMESTAMP    NULL    DEFAULT CURRENT_TIMESTAMP,
  STATUS_ID INT          NOT NULL DEFAULT 1 COMMENT 'CODE. ',
  PRIMARY KEY (LOG_ID)
);

-- 10. PRODUCT 테이블
CREATE TABLE PRODUCT(
  PRODUCT_ID   VARCHAR(20)                        NOT NULL,
  PRODUCT_NAME VARCHAR(100)                       NOT NULL,
  TARGET       VARCHAR(100)                       NULL    ,
  CURRENCY     VARCHAR(3)                         NOT NULL DEFAULT 'KRW',
  PRICE        DECIMAL(10,2)                      NOT NULL DEFAULT 0,
  PRICE_KOR    DECIMAL(10,0)                      NOT NULL DEFAULT 0,
  COST         DECIMAL(10,0)                      NOT NULL DEFAULT 0 COMMENT 'KRW',
  YOUTUBE      TEXT                               NULL     COMMENT 'URL',
  DEV_DATE     VARCHAR(7)                         NOT NULL COMMENT 'YYYYMM',
  STATUS       ENUM ('AVAILABLE', 'DISCONTINUED') NOT NULL DEFAULT 'AVAILABLE',
  MEMO         TEXT                               NULL    ,
  SYS_ID       INT                                NOT NULL DEFAULT 1,
  PRIMARY KEY (PRODUCT_ID)
);

-- 11. ORDERS 테이블 (ORDER 예약어 회피를 위해 명칭 유지 시 백틱 사용)
CREATE TABLE `ORDERS`(
  ORDER_ID    VARCHAR(100)                                                         NOT NULL COMMENT 'CUSTOMERID,YYMMDD,COUNT',
  CUSTOMER_ID VARCHAR(20)                                                          NOT NULL,
  DATE        TIMESTAMP                                                            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CURRENCY    VARCHAR(3)                                                           NULL     DEFAULT 'KRW',
  ORI_PRICE   DECIMAL(10,2)                                                        NOT NULL,
  FIN_PRICE   DECIMAL(10,2)                                                        NOT NULL,
  DIS_AMOUNT  DECIMAL(10,2)                                                        NULL    ,
  DIS_RATE    DECIMAL(5,2)                                                         NULL    ,
  PAYMENT     ENUM('CASH','CREDIT','TRANSFER')                                     NOT NULL,
  STATUS      ENUM('ORDERED','PAID','PACKING','DELIVERING','DELIVERED','CANCELLED') NULL DEFAULT 'ORDERED',
  MEMO        TEXT                                                                 NULL    ,
  SYS_ID      INT                                                                  NOT NULL DEFAULT 1,
  PRIMARY KEY (ORDER_ID)
);

-- 12. ORDER_DETAIL 테이블
CREATE TABLE ORDER_DETAIL(
  ORDER_ID   VARCHAR(100)  NOT NULL,
  ORDER_ROW  INT           NOT NULL DEFAULT 1,
  PRODUCT_ID VARCHAR(20)   NOT NULL,
  AMOUNT     INT           NOT NULL,
  CURRENCY   VARCHAR(3)    NOT NULL DEFAULT 'KRW',
  PRICE      DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ORDER_ID, ORDER_ROW)
);

-- 13. PURCHASE 테이블
CREATE TABLE PURCHASE(
  PURCHASE_ID VARCHAR(100)                                                         NOT NULL,
  CUSTOMER_ID VARCHAR(20)                                                          NOT NULL,
  DATE        TIMESTAMP                                                            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ORI_PRICE   DECIMAL(10,0)                                                        NOT NULL,
  FIN_PRICE   DECIMAL(10,0)                                                        NOT NULL,
  DIS_AMOUNT  DECIMAL(10,0)                                                        NULL    ,
  DIS_RATE    DECIMAL(5,2)                                                         NULL    ,
  PAYMENT     ENUM('CASH','CREDIT','TRANSFER')                                     NULL    ,
  STATUS      ENUM('ORDERED','PAID','PACKING','DELIVERING','DELIVERED','CANCELLED') NOT NULL DEFAULT 'ORDERED',
  MEMO        TEXT                                                                 NULL    ,
  SYS_ID      INT                                                                  NOT NULL DEFAULT 1,
  PRIMARY KEY (PURCHASE_ID)
);

-- 14. PURCHASE_DETAIL 테이블
CREATE TABLE PURCHASE_DETAIL(
  PURCHASE_ID  VARCHAR(100)  NOT NULL,
  PURCHASE_ROW INT           NOT NULL DEFAULT 1,
  PRODUCT_ID   VARCHAR(20)   NOT NULL,
  AMOUNT       INT           NOT NULL DEFAULT 1,
  PRICE        DECIMAL(10,0) NOT NULL,
  SYS_ID       INT           NOT NULL DEFAULT 1,
  PRIMARY KEY (PURCHASE_ID, PURCHASE_ROW)
);

-- 15. WEATHER 테이블
CREATE TABLE WEATHER(
  LOCATION  VARCHAR(50)         NOT NULL,
  TEMP      DECIMAL(5,2)        NULL    ,
  DATE      DATE                NULL    ,
  HUMI      DECIMAL(5,2)        NULL    ,
  SUN_R     TIME                NULL    ,
  SUN_S     TIME                NULL    ,
  RAIN      DECIMAL(6,2)        NULL    ,
  SNOW      DECIMAL(6,2)        NULL    ,
  TIME      TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DATA_FROM ENUM('WEB','CHECK') NOT NULL DEFAULT 'CHECK',
  PRIMARY KEY (LOCATION, TIME)
);

-- 16. 로그성 테이블들 
CREATE TABLE PRODUCT_COST_LOG(
  PRODUCT_ID VARCHAR(20)   NOT NULL,
  DATE       DATE          NOT NULL,
  COST       DECIMAL(10,0) NOT NULL,
  SYS_ID     INT           NOT NULL DEFAULT 1,
  PRIMARY KEY (PRODUCT_ID, DATE)
);

CREATE TABLE PRODUCT_PRICE_LOG(
  PRODUCT_ID VARCHAR(20)   NOT NULL,
  DATE       DATE          NOT NULL,
  CURRENCY   VARCHAR(3)    NOT NULL DEFAULT 'KRW',
  PRICE      DECIMAL(10,2) NULL    ,
  SYS_ID     INT           NOT NULL DEFAULT 1,
  PRIMARY KEY (PRODUCT_ID, DATE)
);

-- ---------------------------------------------------------
-- 17. 외래키 설정 (관계 형성)
-- ---------------------------------------------------------
-- 1. 고객 메모 관련
ALTER TABLE CUSTOMER_MEMO  ADD CONSTRAINT FK_CUSTOMER_TO_CUSTOMER_MEMO    FOREIGN KEY (CUSTOMER_ID)    REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE CUSTOMER_MEMO  ADD CONSTRAINT FK_USER_TO_CUSTOMER_MEMO        FOREIGN KEY (SYS_ID)         REFERENCES USER (SYS_ID);

-- 2. 제품 로그 관련
ALTER TABLE PRODUCT_COST_LOG  ADD CONSTRAINT FK_PRODUCT_TO_PRODUCT_COST_LOG    FOREIGN KEY (PRODUCT_ID)    REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PRODUCT_COST_LOG  ADD CONSTRAINT FK_USER_TO_PRODUCT_COST_LOG        FOREIGN KEY (SYS_ID)         REFERENCES USER (SYS_ID);
ALTER TABLE PRODUCT_PRICE_LOG ADD CONSTRAINT FK_PRODUCT_TO_PRODUCT_PRICE_LOG   FOREIGN KEY (PRODUCT_ID)    REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PRODUCT_PRICE_LOG ADD CONSTRAINT FK_USER_TO_PRODUCT_PRICE_LOG       FOREIGN KEY (SYS_ID)         REFERENCES USER (SYS_ID);
ALTER TABLE PRODUCT           ADD CONSTRAINT FK_USER_TO_PRODUCT               FOREIGN KEY (SYS_ID)         REFERENCES USER (SYS_ID);

-- 3. 주문 관련 (ORDERS)
ALTER TABLE ORDERS       ADD CONSTRAINT FK_CUSTOMER_TO_ORDERS    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE ORDERS       ADD CONSTRAINT FK_USER_TO_ORDERS        FOREIGN KEY (SYS_ID)      REFERENCES USER (SYS_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_ORDERS_TO_ORDER_DETAIL FOREIGN KEY (ORDER_ID)    REFERENCES ORDERS (ORDER_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_PRODUCT_TO_ORDER_DETAIL FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);

-- 4. 구매 관련 (PURCHASE)
ALTER TABLE PURCHASE        ADD CONSTRAINT FK_CUSTOMER_TO_PURCHASE        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE PURCHASE        ADD CONSTRAINT FK_USER_TO_PURCHASE            FOREIGN KEY (SYS_ID)      REFERENCES USER (SYS_ID);
ALTER TABLE PURCHASE_DETAIL ADD CONSTRAINT FK_PURCHASE_TO_PURCHASE_DETAIL FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE (PURCHASE_ID);
ALTER TABLE PURCHASE_DETAIL ADD CONSTRAINT FK_PRODUCT_TO_PURCHASE_DETAIL  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PURCHASE_DETAIL ADD CONSTRAINT FK_USER_TO_PURCHASE_DETAIL     FOREIGN KEY (SYS_ID)      REFERENCES USER (SYS_ID);

-- 5. 벌통 관리 관련
ALTER TABLE HIVE_INSTALL    ADD CONSTRAINT FK_HIVE_TO_HIVE_INSTALL    FOREIGN KEY (HIVE_ID)    REFERENCES HIVE (HIVE_ID);
ALTER TABLE HIVE_INSTALL    ADD CONSTRAINT FK_PRODUCT_TO_HIVE_INSTALL FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE HIVE_INSTALL    ADD CONSTRAINT FK_USER_TO_HIVE_INSTALL    FOREIGN KEY (SYS_ID)     REFERENCES USER (SYS_ID);

ALTER TABLE HIVE_INSPECTION ADD CONSTRAINT FK_HIVE_TO_HIVE_INSPECTION    FOREIGN KEY (HIVE_ID)   REFERENCES HIVE (HIVE_ID);
ALTER TABLE HIVE_INSPECTION ADD CONSTRAINT FK_HIVE_STATUS_TO_HIVE_INSPECTION FOREIGN KEY (STATUS_ID) REFERENCES HIVE_STATUS (STATUS_ID);
ALTER TABLE HIVE_INSPECTION ADD CONSTRAINT FK_USER_TO_HIVE_INSPECTION    FOREIGN KEY (SYS_ID)    REFERENCES USER (SYS_ID);

-- 6. 센서 및 로그 관련
ALTER TABLE HIVE_STATUS_LOG ADD CONSTRAINT FK_HIVE_TO_HIVE_STATUS_LOG        FOREIGN KEY (HIVE_ID)   REFERENCES HIVE (HIVE_ID);
ALTER TABLE HIVE_STATUS_LOG ADD CONSTRAINT FK_HIVE_STATUS_TO_HIVE_STATUS_LOG FOREIGN KEY (STATUS_ID) REFERENCES HIVE_STATUS (STATUS_ID);


-- ---------------------------------------------------------
-- 18. 초기 데이터
-- ---------------------------------------------------------

INSERT INTO HIVE_STATUS (STATUS_ID, STATUS_NAME) VALUES (1, '정상'), (2, '점검 필요'), (3, '분봉 조짐'), (4, '병해충 발생');
INSERT INTO USER (LOGIN_ID, PASSWORD, ROLE) VALUES ('admin', 'admin123', 'ADMIN');